
AUTH0_DOMAIN=zoegeop.auth0.com
API_AUDIENCE=castingagency
CLIENT_ID=CLIENT_ID_HERE
CLIENT_SECRECT=CLIENT_SECRECT_HERE
DATABASE_URL=postgresql://castingagency:castingagency@localhost:5432/castingagency